### ISSUE TITLE
ValidEmail2::Address.new does not allow nil to be passed now

### ISSUE THREAD

**Issue by nijikon** [lisinge/valid_email2#102]
https://github.com/lisinge/valid_email2/commit/5221e411b01ee84eaf6d3e32bd2eae01ce9271f1 introduced an issue. When you pass `nil` to `ValidEmail2::Address.new` it errors. I think that we should fail fast here if nil is passed.

```
irb(main):001:0> ValidEmail2::Address.new(nil)
NoMethodError: undefined method `each_char' for nil:NilClass
```

This is the offender https://github.com/lisinge/valid_email2/blob/master/lib/valid_email2/address.rb#L69

**Comment by lisinge** [comment]
Thanks! Fixed and released v2.2.1
