### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by FireFart** [lisinge/valid_email2#111]
@lisinge there are some false positives in the disposable file. It would be great if you can remove them or implement a whitelist the users can overwrite.

`com.ar`: This matches all domains ending in `com.ar` which is wrong in my opinion. Also `yandex.com` is a valid email provider that should be removed

**Comment by lisinge** [comment]
I would happily accept a PR that removes all the false positives

**Comment by FireFart** [comment]
@lisinge I did the whitelist approach in the linked PR

**Comment by lisinge** [comment]
Thanks! I replied to your PR!
