### ISSUE TITLE
Rubocop unexpected token tCOLON

### ISSUE THREAD

**Issue by andlrb** [lisinge/valid_email2#114]
Hello! 

It seems Rubocop is not very happy with the syntax that is used in the email validation.
```
validates :email, presence: true, "valid_email_2/email": true
```
By using this line Rubocop finds the following offence:
```
Lint/Syntax: unexpected token tCOLON
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
validates :email, presence: true, "valid_email_2/email": true
                                                       ^
```

A workaround for this is using a hashrocket instead of a colon.
```
validates :email, presence: true, "valid_email_2/email" => true
```

Are there any benefits in using a hashrocker or why exactly is Rubocop not happy with the colon? I didn't receive any errors from Rails in my specs or while running the application with the original code.

**Comment by lisinge** [comment]
If memory serves my correct then i think symbol style hash keys were introduced in ruby 1.9.
I don't know exactly when string symbol(i don't know the proper name for it) style keys were introduced though, like the one we have in our examples. It didn't use to work, then you had to use the hashrocket style when the key was a string, like your workaround.

Looking at the error rubycop produces i would say it was maybe introduced in ruby 2.2? (Edit; yes it was introduced in ruby 2.2).
Anyway, as far as i know there is no real advantage to using the hashrocket, it's an old and too me uglier syntax than the newer colon style syntax.
The new style is not compatible with ruby 2.1 but if you are fine with that then there shouldn't be any problem.

And judging by the error rubocop produces you should be able to get rid of the lint error by setting `TargetRubyVersion parameter, under AllCops`

**Comment by lisinge** [comment]
I will close this issue as i believe it's not really an issue with the gem in question. Feel free to open a new issue of you think otherwise or have any other issues
