### ISSUE TITLE
Syntax Error on Ruby 2.1.2p95 - How to fix it?

### ISSUE THREAD

**Issue by pushkargaikwad** [lisinge/valid_email2#117]
I can see the gem being tested from Ruby v 2.2 and above. I am using Ruby 2.1.2p95 and while deploying

`validates :email, 'valid_email_2/email': { mx: true, disposable: true, disallow_subaddressing: true}`
in user.rb created by devise, I am geting Syntax error.

```
syntax error, unexpected ':', expecting keyword_end
... :email, 'valid_email_2/email': { mx: true, disposable: true...
```

How to resolve this (other than upgrading Ruby on the server?

**Comment by lisinge** [comment]
I'm pretty sure its the string/symbol syntax that's compatible with 2.1. All you should need to do is to use the old rocket syntax instead `"valid_email_2/email" => { mc: true, disposable: true, disallow_subaddressing: true }`

**Comment by pushkargaikwad** [comment]
Perfect, solved the issue.
