### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by flayspammers** [lisinge/valid_email2#120]
This listing prevents signup from a disposable email address service?  

oh noes!

What will I do?

Gee, maybe I'll treat a non-listed email service as disposable.

And why would I do that?

BECAUSE

the kind of cretinous fops who blacklist self-protection services are typically the scum bent on spamming me - a behavior I will vociferously resist.

YOU FAIL

Your policy is INANITY

**Comment by lisinge** [comment]
Hi flay.

Thanks for your kind words.
