### ISSUE TITLE
Invalid addresses like mail@domain..com get validate

### ISSUE THREAD

**Issue by sebastian-julius** [lisinge/valid_email2#17]
With the update introduced in version 1.1.5, emails with multiple dots in the domain name get validated.  

mail@domain..com
mail@domain...something..com

In fact, they're invalid.

**Comment by lisinge** [comment]
So sorry about that. I've pushed a fix and added a simple test.
I've also pushed v1.1.6 to rubygems whith the fix.

Thanks for bringing this to my attention!

**Comment by sebastian-julius** [comment]
No problem. Thanks for the nice gem!
