### ISSUE TITLE
Regular email provider on disposable email list

### ISSUE THREAD

**Issue by mfly** [lisinge/valid_email2#34]
The "poczta.onet.pl" domain belongs to e-mail service provided by the biggest Polish web portal - onet.pl. It shouldn't be blacklisted.

It was included in this commit:
- https://github.com/lisinge/valid_email2/commit/468f8ffbe6396a3590189717957a8148f323c63d
  - Which adds domains from: https://github.com/FGRibreau/mailchecker/blob/master/list.json
    - And the source of this is probably: https://github.com/lavab/disposable/blob/master/domains.txt
      - Going deeper we get: https://gist.github.com/michenriksen/8710649 (with a comment about this issue: https://gist.github.com/michenriksen/8710649#gistcomment-1560033)
      - and https://github.com/ivolo/disposable-email-domains/blob/master/index.json
        - which source is https://github.com/martenson/disposable-email-domains/blob/master/disposable_email_blacklist.conf
            - and at the end http://www.digitalfaq.com/forum/web-tech/5050-throwaway-email-block.html

As you can see, the problem has quite impressive roots. I propose removing the domain from the list, implementing domain whitelist to quickly patch future mistakes, and also paying more attention to validation before blacklisting a domain.

Possible workarounds:
- downgrade gem to 1.1.9
- disable disposable email validation

**Comment by lisinge** [comment]
Thanks for bringing this up and i'm sorry that poczta.onet.pl sneaked through.
I'm usually always checking all the additions to the list so that this wouldn't happen but the PR in question included over 500 new providers and i didn't have time to check them all.

I've pushed v1.1.11 to rubygems which fixes this issue.

**Comment by mpokrywka** [comment]
onet.pl & poczta.onet.pl are again on the list of disposable mails, please those domains from disposable_emails.yml

**Comment by lisinge** [comment]
@mpokrywka Thanks, i've removed them
