### ISSUE TITLE
Dots in GMail addresses

### ISSUE THREAD

**Issue by rivella50** [lisinge/valid_email2#36]
Hi, 
what do you think about extending your library in order to also support validating email addresses which only differ in moveable/number of dots in the account name?
http://www.makeuseof.com/tag/1-awesome-gmail-tip-you-dont-know-about-seriously/

The domain names (gmail.com, googlemail.com, ...) to check against could be stored in an additional yaml file.
The question is: Would this work without having to store the "raw" (i.e. without any dots at all) version of the account part of the email address in an additional database column?

Thanks for considering this and great work btw.
Greets
valley

**Comment by lisinge** [comment]
I'm not sure i understand what you mean. Email addresses with dots are valid according to the library:
```ruby
irb(main):001:0> address = ValidEmail2::Address.new("l.i.s.i.n.g.e@gmail.com")
=> #<ValidEmail2::Address:0x007fc95ba7df60 @parse_error=false, @raw_address="l.i.s.i.n.g.e@gmail.com", @address=#<Mail::Address:70251401441180 Address: |l.i.s.i.n.g.e@gmail.com| >>
irb(main):002:0> address.valid?
=> true
````

**Comment by rivella50** [comment]
Yeah, sorry, this is probably not the best idea i just had.
My thoughts were that the gem could verify against the email addresses of all users in database, if there exists already the same email address if all dots are removed in the account name, e.g.
G.eorgeBush@gmail.com would be equal to Ge.orgeBush@gmail.com, and therefore blocked if a user would try to register with the 2nd email address.
But that's not a task for this gem, i guess ;-)

**Comment by lisinge** [comment]
Oh, now i understand.

It's not a bad idea but like you say, its out of scope for this gem. You can accomplish this with a custom validation.

**Comment by pjmartorell** [comment]
@micke regarding this issue, I think that `disallow_subaddressing` option is at the same level as this one. It depends on the mail server to take subaddressing into account or not, so `johndoe+spam@exmaple.com` and `johndoe@example.com` can be totally different email accounts depending on the mail server. The same happens with emails containing dots, Gmail considers `johndoe@example.com` and `john.doe@example.com` are the same email account, but other mail servers not. Taking into account that Gmail is the most widely used mailing service (https://financesonline.com/number-of-email-users/#B) with more than 1.5 billion active accounts it would be really appreciated if you could reconsider your decision. I could provide a PR for this if you agree.

**Comment by micke** [comment]
@pjmartorell Hi, i think one problem with classifying addresses with dots in them as subaddresses is that gmail still allows you to include a dot in your address when registering as seen in this screenshot:
![image](https://user-images.githubusercontent.com/22270/76953295-c5f75200-690e-11ea-9241-985737c56571.png)

So a user could legitimately have a dot in their address.

**Comment by pjmartorell** [comment]
@micke Yes, when you register micke.test@gmail.com you also own all their possible dotted versions, including the one without dots. I wouldn't disallow it by default, but as an option, as you can see in my PR.
