### ISSUE TITLE
Subdomain test?

### ISSUE THREAD

**Issue by jrasanen** [lisinge/valid_email2#40]
Some disposable email providers generate a random subdomain too.

Like our database has emails like: ffq24627@db1000.pp.ua, ybqomvdb@loh.pp.ua, ybqomvdb@loh.pp.ua, oh72m6h7@mox.pp.ua, ...

At the moment these *.pp.ua emails passes the validations

**Comment by lisinge** [comment]
Version 1.2.0 includes validation of subdomains
