### ISSUE TITLE
Conflict on the EmailValidator with another gem (devise_token_auth)

### ISSUE THREAD

**Issue by xdmx** [lisinge/valid_email2#46]
Steps to reproduce with rails 5:

```
rails new testemail -B -d postgresql
```

Add to Gemfile:

```
gem 'devise_token_auth', github: 'lynndylanhurley/devise_token_auth'
gem 'valid_email2', '~> 1.2.3'
```

create app/model/invitation.rb

```
class Invitation
  include ActiveModel::Model

  attr_accessor :email

  validates :email, email: { mx: true, disposable: true }
end
```

```
bundle install
git init
heroku create
git add .
git commit -m "init"
git push heroku master
```

```
# rails c
x = Invitation.new email: 'c1143256@trbvn.com'
x.valid? => false

# heroku run console
x = Invitation.new email: 'c1143256@trbvn.com'
x.valid? => true
```

The problem seems to be that devise_token_auth also has an [EmailValidator](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/validators/email_validator.rb) which overwrites valid_email2's validator.

Is there a way to force to use valid_email2 and not devise_token_auth?

I've tried to change the gemfile with

```
gem 'valid_email2', '~> 1.2.3'
```

and adding `require 'valid_email2` after `Bundler.require(*Rails.groups)` in `config/application.rb` but still loads the wrong one

**Comment by lisinge** [comment]
Sorry, i completely forgot to attend to this issue.

I'm open to move `EmailValidator` under the `ValidEmail2` namespace, this would need to be released as version 2.0.0 as to not break semver. I'm swamped with other stuff right now so a PR is definitely welcomed.

**Comment by fredngo** [comment]
Hello @lisinge! I submit this PR for your consideration: https://github.com/lisinge/valid_email2/pull/79

**Comment by fredngo** [comment]
Looks like this issue can now be closed :)

**Comment by lisinge** [comment]
I just pushed v2.0.0 to rubygems which includes @fredngo's pr which namespaces the validator.
See https://github.com/lisinge/valid_email2#upgrading-to-v200 for upgrade instructions

**Comment by andystu** [comment]
under rails 5, bundle this gem already, and then I put => validates :email, presence: true, 'valid_email_2/email': true
into my user model, but get error => Unknown validator: 'ValidEmail2::EmailValidator'

**Comment by lisinge** [comment]
@andystu Are you sure you are running version 2.0.0?
