### ISSUE TITLE
Custom user additions to blacklist?

### ISSUE THREAD

**Issue by mklnz** [lisinge/valid_email2#55]
Please add:
throwam.com to the disposable list, I see throam.com in the list but not thro**w**am.com

**Comment by mklnz** [comment]
Sorry I see the it's missing from the upstream source as well. I have reported this issue on the other repo.

Is there some way to add user defined domains to be blacklisted?

**Comment by lisinge** [comment]
You can use the blacklist feature, the README mentions it but it's better described in the PR https://github.com/lisinge/valid_email2/pull/5

I will add throwam.com to the list and push a update.
