### ISSUE TITLE
Don't include example.com in disposable_emails.yml

### ISSUE THREAD

**Issue by kenn** [lisinge/valid_email2#59]
`example.com` is a special reserved domain defined in RFC 2606 that no provider can take.

- It's not "disposable" - it's just never unreachable. I think the definition of "disposable" should be "email address that is reachable," not a random unreachable addresses. Otherwise `disposable_emails.yml` has to include any random string like `fasdfatyiehjdnbsdfasd.com` which is valid in syntax but also unreachable in the same sense as `example.com`.
- Many of us use `example.com` domain for test fixtures / factories (because that's what it's intended for!), and all tests start to fail when we introduce this gem with `disposable: true`

**Comment by lisinge** [comment]
Good spot, thanks!

I removed example.com and release v1.2.9.

**Comment by kenn** [comment]
This is back as of 2.1.0 - example.com is added back on line 1152 in `disposable_emails.yml`.

Should I add a test so it will never happen again?

**Comment by kenn** [comment]
Or, override with whitelist config?

**Comment by kenn** [comment]
At this moment, I've monkey-patches with the following line in an initializer:

```ruby
ValidEmail2.disposable_emails.delete('example.com')
```

**Comment by lisinge** [comment]
@kenn Sorry for the late reply.
I've removed example.com again and added a test so that it can't' sneak itself in again.
Update to version 2.1.1 and you can remove your monkey-patch
Thanks!
