### ISSUE TITLE
Is it intended that test@.com is a valid email address?

### ISSUE THREAD

**Issue by sebastian-julius** [lisinge/valid_email2#63]
We discovered that `test@.com` is a valid email address by the definition of this project. Is there a reason for that? No mailer in the world could deliver a message to such an email address.

Thanks

**Comment by sebastian-julius** [comment]
nice, thanks a lot 👍  that was a quick one

**Comment by lisinge** [comment]
Your are completely correct, that was not the intended behaviour.
I've fixed the test and the implementation and i released v1.2.1 that includes this fix.

Thanks for bringing this to my attention!
