### ISSUE TITLE
valid_email2 is not validating the emails correctly

### ISSUE THREAD

**Issue by sajjadmurtaza** [lisinge/valid_email2#88]
I tried to validate emails using `valid_email2` gem (without ActiveModel) but i noticed there is something that needs to improve.

Look at following examples **(Especially email address)**

1- 
```
 > email
   => "goel.urvashi1@gmail+blinkist.com" 
 > ValidEmail2::Address.new(email).valid?
   => true 

```
> Why?

2- 
```
 > email
   => "jacoblarsonband@yahoo.comfargoasfsn123!"
 > ValidEmail2::Address.new(email).valid?
   => true 

```
> Why it's saying valid email?

and also for `email = "bengmr@msn-.com"` 

any suggestion will be appreciated. Thanks

**Comment by lisinge** [comment]
I've release v2.1.0 to rubygems with the fix. Thanks!
