### ISSUE TITLE
Error loading the gem.

### ISSUE THREAD

**Issue by utkarshrai003** [lisinge/valid_email2#91]
I added the gem to my gem file and bundled it. When i try to open up the console, I get the following error.

**Gem Load Error is: superclass mismatch for class EmailValidator**

I opened up the gem and commented line 2nd in lib/valid_email2.rb which says 

**require "email_validator" # Backwards-compatibility shim**

then it works fine. Any idea why is this hapenning ?

**Comment by lisinge** [comment]
What do you have in your gemfile?

It sounds like you already have a `EmailValidator` class defined elsewhere. Possibly in another gem

**Comment by utkarshrai003** [comment]
yes, I guess so. But what can be done for it. Right now, I have patched this in my lib directory and loading my gem from lib.

**Comment by grammakov** [comment]
There's a gem called 'email_validator' which may be causing such conflicts. At least that's what's happening on my end.

**Comment by lisinge** [comment]
We've actually already deprecated the global `EmailValidator` class in favour of a namespaced class in https://github.com/lisinge/valid_email2/pull/79.

I guess it's time to actually pull the trigger and remove it completely to get rid of these last errors like the one you are getting here.

I just have some things i want to get in before i push a new release but i will update here once a release have been pushed.

**Comment by lisinge** [comment]
I've released version 2.2.0 with the shim removed https://github.com/lisinge/valid_email2/commit/6d7a14d097adcac5c433c0d846551e57c0dd77d4

Please give it a try!
