### ISSUE TITLE
Overriding disposable emails

### ISSUE THREAD

**Issue by beNjiox** [lisinge/valid_email2#96]
Hello,

First of all: Thanks for the nice gem!

I'm trying to find a way to override the list of disposable emails.
qq.com is marked as being disposable emails but I've found that our business does have legit paying customers using this email.
I've tried to create my own `vendor/disposable_emails.yml` with the list you came up with, minus qq.com but it does not seem to work.

(Note: I'm not sure why this is marked as disposable btw, as this seem to be a more [than legit email provider](https://www.quora.com/Are-QQMail-accounts-permanent/answer/Chris-Eneman))

Any pointers for me?

Thanks!

**Comment by lisinge** [comment]
Hi. I've accepted your PR and will try to make sure that qq.com doesn't end up in the list again.

Thanks!

**Comment by lisinge** [comment]
I've pushed version v2.1.2 to rubygems with this fixed!
